batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202310201149
train_epochs: 10
train_workers: 40
vocab: ksNCfl?)Arx7yH*!Bt9n#8boqGR&pS2;zOMjd:0YmgD/Q1FW+X3,'ZE"i6.cIPh(L-TKuVaeJ54vwU
width: 128
